apiVersion: v1
kind: PersistentVolume
metadata:
  name: screeps-data-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/screeps"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: screeps-data-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 45Gi