apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "screeps.fullname" . }}-pod-reader
  labels:
    {{- include "screeps.labels" . | nindent 4 }}
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch