apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "screeps.fullname" . }}-pod-reader
  labels:
    {{- include "screeps.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "screeps.fullname" . }}-pod-reader
subjects:
- kind: ServiceAccount
  name: {{ include "screeps.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}